### ISSUE TITLE
Kicad 6 installing

### ISSUE THREAD

**Issue by AntonioBanditoz** [ma-ha/kicad-laser-stencil-plugin#1]
Hi. I ran into a problem installing a plugin in Kicad 6, I placed the plugin in the specified directory. Thanks for your help.

**Comment by ma-ha** [comment]
Hi, seems the PlugIn directory changed in KiCad 6: If you open Pcb Editor and "Tool" menu > "External Plugins" > "Open Plugin Directory", you will see where KiCad is searching for plugins. I've copied the **laser-stencil** folder into **~/.local/share/kicad/6.0/scripting/plugins** and it worked fine. Could you please try?

**Comment by AntonioBanditoz** [comment]
Hi, opened the plugins directory from Kicad, renamed the folder to Laser and with its contents copied there, updated the plugins, no luck, restarted Kicad, still does not see the plugin. I have no share folder in the directory you specified, can you specify the full path? Thank you.

**Comment by ma-ha** [comment]
Which operating system do you have? Win? Linux? Mac?
On Linux following should work:
```
git clone https://github.com/ma-ha/kicad-laser-stencil-plugin.git
cd kicad-laser-stencil-plugin
cp -r laser-stencil ~/.local/share/kicad/6.0/scripting/plugins
```

**Comment by AntonioBanditoz** [comment]
Windows 10

**Comment by ma-ha** [comment]
Sorry for delay -- I own no Win PC ;-) 
On Windows install works for me like this: 

- Download this repository as Zip file and extract it
- From the extracted ZIP, copy the folder **laser-stencil** with Ctrl-C
- Open to the KiCad installation folder, e.g. C:/Program Files/KiCad/6.0
- Navigate to **share/kicad/scripting/plugins**
- paste the **laser-stencil** into the plugins folder with Ctrl-V
- In the PCB Editor open the "Tools" Menu, there the "External Plugins" and click "Refresh Plugins"

The laser stencil icon should now appear in PCB Editor (most right). Tested, working.

**Comment by ma-ha** [comment]
seems to work ;-)
